<?php
/*
------------------------------------------------------------------------
MIT License

Copyright (c) 2016 - 2017 Dominik Procházka

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
------------------------------------------------------------------------
* Author: Dominik Procházka
* File: English.php
* Filepath: /_core/langs/English.php
*/

if(!defined("AUTHORIZED")) { die("Access Denied"); }

if(empty($l) || !isset($l) || !is_array($l)) $l = array();

$langCode = "en";
$localeCode = "en_US";
$l = array_merge($l, array(
  "LANG" => "English",
  "LANGUAGE" => "English",
  "RENDERTIME" => "Generated in <b><rendertime>%%%WEB_RENDER_TIME%%%%</rendertime>s</b>.",
  "JAVASCRIPT_DISABLED" => "Oh no! Where is JavaScript? Your web browser does not support JavaScript. Please change your web browser.",
  "P_REGISTER_TITLE" => "Registration",
  "P_REGISTER_L1" => "Username",
  "P_REGISTER_L2" => "Password",
  "P_REGISTER_L3" => "Password <i>(again)</i>",
  "P_REGISTER_L4" => "E-Mail address",
  "P_REGISTER_L5" => "E-Mail address <i>(again)</i>",
  "P_REGISTER_E1" => "You haven\'t filled in all fields.",
  "P_REGISTER_E2" => "Username must contain at least 3 characters.",
  "P_REGISTER_E3" => "Passwords doesn\'t match..",
  "P_REGISTER_E4" => "Invalid E-Mail address.",
  "P_REGISTER_E5" => "E-Mail addresses doesn\'t match.",
  "P_REGISTER_E6" => "Username already in use.",
  "P_REGISTER_E7" => "E-Mail address already in use.",
  "P_REGISTER_E8" => "Password must contain at least 6 characters.",
  "P_REGISTER_OK" => "Account successfully registered, activation message was sent to your E-Mail.",
  "P_REGISTER_B1" => "Have account yet",
  "P_REGISTER_B2" => "Register",
  "P_REGISTER_T1" => "Activation message will be send to your E-Mail.",
  "P_LOGIN_TITLE" => "Login",
  "P_LOGIN_L1" => "Username",
  "P_LOGIN_L2" => "Password",
  "P_LOGIN_L3" => "Remember me",
  "P_LOGIN_B1" => "I need to register",
  "P_LOGIN_B2" => "Login",
  "P_LOGIN_B3" => "Forgot password?",
  "P_LOGIN_E1" => "You haven\'t filled in all fields.",
  "P_LOGIN_E2" => "Invalid username and password combination.",
  "P_LOGIN_E3" => "Account <b>%s</b> wasn\'t activaed yet, <a href=\'%s\'>activate account</a>.",
  "P_LOGIN_E4" => "Account <b>%s</b> is blocked, for more info check your E-Mail inbox, connected with this user account.",
  "P_LOGIN_OK" => "Successfully logged in as <b>%s</b>, you will be redirected.",
  "P_ACTIVE_TITLE" => "User activation",
  "P_ACTIVE_L1" => "Username",
  "P_ACTIVE_B1" => "Login",
  "P_ACTIVE_B2" => "Send activation E-Mail",
  "P_ACTIVE_E1" => "Username wasn\'t filled in.",
  "P_ACTIVE_E2" => "User account <b>%s</b> does not exist.",
  "P_ACTIVE_E3" => "User account already activated.",
  "P_ACTIVE_E4" => "Account <b>%s</b> is blocked, for more info check your E-Mail inbox, connected with this user account.",
  "P_ACTIVE_E5" => "Link validity expired. <a href=\'%s\'>Generate new activation message.</a>",
  "P_ACTIVE_OK1" => "Activation message was sent to your E-Mail.",
  "P_ACTIVE_OK2" => "User account <b>%s</b>, was successfully activated, now you can log in.",
  "P_PASSWORD_TITLE" => "Forgot password?",
  "P_PASSWORD_L1" => "Username",
  "P_PASSWORD_L2" => "E-Mail address",
  "P_PASSWORD_L3" => "New password",
  "P_PASSWORD_L4" => "New password <i>(again</i>)",
  "P_PASSWORD_T1" => "Fill in username or E-Mail address connected with this account. Password change message will be send to your E-Mail address.",
  "P_PASSWORD_T2" => "New password request was successfully deleted.",
  "P_PASSWORD_B1" => "Back to login",
  "P_PASSWORD_B2" => "Send new password request",
  "P_PASSWORD_B3" => "Cancel new password request",
  "P_PASSWORD_B4" => "Change password",
  "P_PASSWORD_E1" => "You must fill in username or E-Mail connected with this account.",
  "P_PASSWORD_E2" => "User account does not exist.",
  "P_PASSWORD_E3" => "User account is blocked, for more info check your E-Mail inbox, connected with this useer account.",
  "P_PASSWORD_E4" => "Link validity expired. <a href=\'%s\'>Generate new password change request.</a>",
  "P_PASSWORD_E5" => "You must fill in both fields.",
  "P_PASSWORD_E6" => "Passwords does not match.",
  "P_PASSWORD_OK1" => "Password change request successfully generated, link for password change was sent to your E-Mail inbox.",
  "P_PASSWORD_OK2" => "Password was successfully set, now you can login.",
  "P_LOGOUT_TITLE" => "Logout",
  "P_LOGOUT_T1" => "Logout in progress <b>%s</b>, you will be redirected.",
  "P_LOGOUT_T2" => "If the page won\'t show in 10 secs, click here.",
  "P_REDIRECT_TITLE" => "Redirection",
  "P_REDIRECT_T1" => "Link that you used, refers to another websites.",
  "P_REDIRECT_T2" => "For continue, click on the button under this text.",
  "P_REDIRECT_T3" => "You can\'t be redirected, because link you used is no longer valid.",
  "P_REDIRECT_B1" => "Continue to external website.",
  "P_REDIRECT_B2" => "Back",
  "P_PROFILE_TITLE" => "User profile - %s",
  "P_PROFILE_L1" => "Registration date:",
  "P_PROFILE_L2" => "User account type:",
  "P_PROFILE_L3" => "Last login:",
  "P_PROFILE_L4" => "Registration date:",
  "P_PROFILE_L5" => "E-Mail address:",
  "P_PROFILE_DESC" => "User description",
  "P_PROFILE_ONLINE" => "Now active",
  "P_PROFILE_AFK" => "Active few seconds ago",
  "P_PROFILE_OFFLINE" => "Inactive",
  "P_PROFILE_EDIT" => "Profile update",
  "P_PROFILE_E1" => "Error, user profile was not found.",
  "PROFILE_NOTEXISTS" => "User does not exist",
  "P_PROFILE_B1" => "Send private message",
  "P_PROFILE_B2" => "Report user",
  "P_GROUPS_TITLE_1" => "User group - %s",
  "P_GROUPS_TITLE_2" => "User groups",
  "P_GROUPS_L1" => "Back to user groups summary",
  "P_GROUPS_T1" => "users",
  "P_GROUPS_T2" => "user",
  "P_GROUPS_T3" => "users",
  "P_GROUPS_USERS_LIST" => "Users in group <i>(%d)</i>:",
  "P_GROUPS_DESC_NONE" => "Users group doesn\'t have any description.",
  "P_REPORT_T1" => "Report",
  "P_REPORT_L1" => "Reported user",
  "P_REPORT_L2" => "Reported comment",
  "P_REPORT_L3" => "Report reason",
  "P_REPORT_OK" => "Report was successfully sent.",
  "P_REPORT_E1" => "Report can\'tt be send.",
  "P_REPORT_B1" => "Report",
  "P_REPORT_B2" => "Do not report",
  "P_SETTINGS_TITLE" => "Configuration",
  "P_SETTINGS_T1" => "Main configuration",
  "P_SETTINGS_T2" => "Password configuration",
  "P_SETTINGS_T3" => "Avatar configuration",
  "P_SETTINGS_T4" => "Profile configuration",
  "P_SETTINGS_T5" => "Device",
  "P_SETTINGS_L1" => "Login username",
  "P_SETTINGS_L2" => "Showed username",
  "P_SETTINGS_L3" => "E.Mail address",
  "P_SETTINGS_L9" => "Website language",
  "P_SETTINGS_L4" => "Your current password",
  "P_SETTINGS_L5" => "New password",
  "P_SETTINGS_L6" => "New password <i>(again)</i>",
  "P_SETTINGS_L7" => "Avatar choice",
  "P_SETTINGS_L7-1" => "Use main avatar",
  "P_SETTINGS_L7-2" => "Use <a href=\'%s\' target=\'_blank\'>gravatar.com</a> <i>(from E-Mail address %s)</i>",
  "P_SETTINGS_L7-3" => "Use uploaded avatr <i>(max. %s, %sx%s)</i>",
  "P_SETTINGS_L8" => "Current avatar",
  "P_SETTINGS_L10" => "Show your E-Mail address?",
  "P_SETTINGS_L10-1" => "Yes",
  "P_SETTINGS_L10-2" => "No",
  "P_SETTINGS_L11" => "User description",
  "P_SETTINGS_L11-1" => "You haven\'t filled in any user description yet, you can do it here.",
  "P_SETTINGS_L12" => "Primary group",
  "P_SETTINGS_L12-1" => "You are member in only one group (<strong>%s</strong>).",
  "P_SETTINGS_L12-2" => "You aren\'t member of any group yet.",
  "P_SETTINGS_B1" => "Save configuration",
  "P_SETTINGS_B2" => "Set new password",
  "P_SETTINGS_B3" => "Set Avatar",
  "P_SETTINGS_B4" => "Update profile",
  "P_SETTINGS_OK1" => "Configuration successfully saved.",
  "P_SETTINGS_OK1-1" => "New E-Mail address successfully set, you can check it by links sent to both E-Mail addresses.",
  "P_SETTINGS_OK2" => "New password successfully set, you can check it by link sent to your E-Mail.",
  "P_SETTINGS_OK3" => "Avatar succesfully set.",
  "P_SETTINGS_OK4" => "Profile configuration successfully saved.",
  "P_SETTINGS_E1" => "You haven\'t filled in all fields.",
  "P_SETTINGS_E2" => "Showed username must contain at least 3 characters, and can\'t contain any special characters.",
  "P_SETTINGS_E3" => "invalid E-Mail address.",
  "P_SETTINGS_E4" => "Invalid current password.",
  "P_SETTINGS_E5" => "Passwords doesn\'t match.",
  "P_SETTINGS_E6" => "Password must contain at least 6 characters.",
  "P_SETTINGS_E7" => "Avatar loading method wasn\'t set.",
  "P_SETTINGS_E8" => "File, that you uploaded isn\'t image.",
  "P_SETTINGS_E9" => "Image must be in format *.png, *.jpg, or *.gif.",
  "P_SETTINGS_E10" => "Image is too large, maximum size of profile image is <b>%s</b>.",
  "P_SETTINGS_E11" => "An error occured in file uploading.",
  "P_SETTINGS_E12" => "Image is too large, maximum image size is <b>%sx%s</b>",
  "P_SETTINGS_PASS_ACCOUNT_TYPE" => "You can not change password on your account.",
  "P_SETTINGS_EMAIL_ACCOUNT_TYPE" => "You can not change E-Mail address on your account.",
  "P_SETTINGS_PASS_BLOCK" => "New password request already created, please check your E-Mail.",
  "P_SETTINGS_PASS_CLOSE" => "Cancel new password request",
  "P_SETTINGS_NO_DEVICE" => "Something went wrong, no device in your user account.",
  "P_SETTINGS_EMAIL_NOTICE" => "E-Mail address authorization will be requested.",
  "P_SETTINGS_EMAIL_CHANGE" => "Activation message was sent to your E-Mail.",
  "P_SETTINGS_EMAIL" => "Authorization neede for E-Mail address change..",
  "P_SETTINGS_EMAIL_BLOCK" => "E-Mail address change already created..",
  "P_SETTINGS_EMAIL_CLOSE" => "I don\'t want to change my E-Mail address.",
  "P_SETTINGS_EMAIL_CHANGE_E" => "E-Mail address change request created.",
  "P_SETTINGS_PASS_CHANGE_E" => "New login password request",
  "P_SETTINGS_DEVICE_T1" => "First login from this device.",
  "P_SETTINGS_DEVICE_T2" => "Last activity from this device.",
  "P_SETTINGS_DEVICE_TABLE_H1" => "Devices",
  "P_SETTINGS_DEVICE_TABLE_H2" => "Time and date",
  "P_SETTINGS_DEVICE_TABLE_H3" => "Action",
  "P_SETTINGS_DEVICE_ACTION_1" => "Trusted",
  "P_SETTINGS_DEVICE_ACTION_2" => "Delete",
  "P_SETTINGS_DEVICE_ACTION_3" => "Block",
  "P_DEVICE_BLOCKED" => "This device was blocked.",
  "P_DEVICE_USED" => "Now using this device.",
  "P_ERROR_T1" => "Page not found",
  "P_ERROR_T2" => "Error - Page not found",
  "P_ERROR_T3" => "This page does not exist.",
  "P_MESSAGES_TITLE" => "Personal messages",
  "P_MESSAGE_T1" => "Accepted",
  "P_MESSAGE_T2" => "Unreaded",
  "P_MESSAGE_T3" => "Important",
  "P_MESSAGE_T4" => "Sent",
  "P_MESSAGE_T5" => "Conversation",
  "P_MESSAGE_T6" => "Sent",
  "P_MESSAGE_T7" => "Seen",
  "P_MESSAGE_T8" => "Back to messages summary",
  "P_MESSAGE_T9" => "Personal message from",
  "P_MESSAGE_T10" => "Seen by user: %s in %s",
  "P_MESSAGE_T11" => "Seen by you in %s",
  "P_MESSAGE_T12" => "Personal message for",
  "P_MESSAGE_T13" => "User %s didn\'t read your message yet.",
  "P_MESSAGE_T14" => "Put your text here..",
  "P_MESSAGE_T15" => "Answer to user %s",
  "P_MESSAGE_T16" => "Send another message to user %s",
  "P_MESSAGE_L1" => "Quote the message text and send it with a new message",
  "P_MESSAGE_L2" => "Conversation (#%s)",
  "P_MESSAGE_L3" => "Recipient",
  "P_MESSAGE_L4" => "Subject",
  "P_MESSAGE_L5" => "Message content",
  "P_MESSAGE_CONVERSATION_OWNER" => "Conversation management",
  "P_MESSAGE_CONVERSATION_INVITED" => "Invited to conversation",
  "P_MESSAGE_UNREAD" => "New",
  "P_MESSAGE_NEXTUSERS_1" => "and another one user",
  "P_MESSAGE_NEXTUSERS_2" => "and another %s users",
  "P_MESSAGE_NEXTUSERS_3" => "and another %s users",
  "P_MESSAGE_TABLE_H1" => "Subject",
  "P_MESSAGE_TABLE_H2" => "Sent by",
  "P_MESSAGE_TABLE_H3" => "Date",
  "P_MESSAGE_TABLE_H4" => "Recipient",
  "P_MESSAGE_NO_MESSAGES_1" => "No new messages",
  "P_MESSAGE_NO_MESSAGES_2" => "No sent messages yet",
  "P_MESSAGE_NO_MESSAGES_3" => "You don\'t have any unseen messages",
  "P_MESSAGE_NO_MESSAGES_4" => "You don\'t have any important messages",
  "P_MESSAGE_B1" => "New message",
  "P_MESSAGE_B2" => "Send message",
  "P_MESSAGE_E1" => "Message cannot be empty.",
  "P_MESSAGE_E2" => "Recipient wasn\'t found in system.",
  "P_MESSAGE_E3" => "All message fields must be filled.",
  "P_MESSAGE_E4" => "You cannot send a message to yourself.",
  "P_MESSAGE_OK1" => "Your message was successfully sent",
  "PLUGIN_USERPANEL_TITLE_1" => "Login",
  "PLUGIN_USERPANEL_TITLE_2" => "Profile - %s",
  "PLUGIN_USERPANEL_L1" => "Username",
  "PLUGIN_USERPANEL_L2" => "Password",
  "PLUGIN_USERPANEL_L3" => "Remember me",
  "PLUGIN_USERPANEL_T1" => "I need to register",
  "PLUGIN_USERPANEL_T2" => "Forgotten password",
  "PLUGIN_USERPANEL_B1" => "Login",
  "PLUGIN_USERPANEL_L4" => "Configuration",
  "PLUGIN_USERPANEL_L5" => "Personal messages",
  "PLUGIN_USERPANEL_L6" => "Administration",
  "PLUGIN_USERPANEL_L7" => "Logout",
  "PLUGIN_GOOGLELOGIN_TITLE" => "Login via Google account",
  "PLUGIN_GOOGLELOGIN_B1" => "Login via",
  "PLUGIN_ONLINEUSERS_TITLE" => "Active users",
  "PLUGIN_FORUM_TITLE" => "Discussion",
  "AS_PLUGIN_DATATABLES_NO_DATA" => "There are no data.",
  "AS_PLUGIN_DATATABLES_BTN_FIRST" => "First",
  "AS_PLUGIN_DATATABLES_BTN_PREV" => "Previous",
  "AS_PLUGIN_DATATABLES_BTN_NEXT" => "Next",
  "AS_PLUGIN_DATATABLES_BTN_LAST" => "Last",
  "COMMENTS_T1" => "Comments",
  "COMMENTS_T2" => "Comment",
  "COMMENTS_T3" => "Comments",
  "COMMENTS_T4" => "No comments",
  "COMMENTS_T5" => "No comments yet.",
  "COMMENTS_T6" => "Comments blocked on this post.",
  "COMMENTS_T7" => "<p class=\'text-danger\'>Do you really want to delete this comment?</p><p class=\'text-danger\'><i><b>(%s):</b> %s</i></p>",
  "COMMENTS_T8" => "Comment update",
  "COMMENTS_T9" => "All comments were loaded.",
  "COMMENTS_L1" => "Back to news summary",
  "COMMENTS_L2" => "Put your text here..",
  "COMMENTS_L3" => "Updated",
  "COMMENTS_E1" => "Comment cannot by empty.",
  "COMMENTS_OK" => "Comment was added.",
  "COMMENTS_OK_E" => "Comment was successfully updated.",
  "COMMENTS_B1" => "Add comment",
  "COMMENTS_B2" => "Yes, I want to delete this comment",
  "COMMENTS_B3" => "No, I don\'t want to",
  "COMMENTS_B4" => "Update comment",
  "COMMENTS_B5" => "Cancel changes",
  "COMMENTS_B6" => "Load all comments",
  "COMMENTS_L4" => "Update",
  "COMMENTS_L5" => "Delete",
  "COMMENTS_L6" => "Report",
  "NEWS_CATEGORIES_T1" => "News category",
  "NEWS_CATEGORIES_T2" => "posts",
  "NEWS_CATEGORIES_T3" => "No category description.",
  "NEWS_CATEGORIES_T4" => "No posts in this category.",
  "NEWS_CATEGORIES_T5" => "Back to category sumamry",
  "NEWS_AUTHOR" => "Author:",
  "NEWS_DATE" => "Added:",
  "NEWS_CAT" => "Category:",
  "NEWS_TITLE" => "News",
  "REPORTS_T1" => "Report",
  "REPORTS_T2" => "Report comment",
  "REPORTS_E1" => "Report content cannot be empty.",
  "MAINTENANCE_T1" => "Maintenance",
  "MAINTENANCE_T2" => "Logged in user <b>%s</b>",
  "MAINTENANCE_ALERT_T1" => "Maintenance mod",
  "MAINTENANCE_ALERT_T2" => "Websites are in maintenance mod. Basic users and visitors cannot entry websites now.",
  "MAINTENANCE_B1" => "Logout",
  "MAINTENANCE_B2" => "Continue to websites",
  "SETUP_T1" => "System instalation",
  "SETUP_S1_T1" => "Choose language",
  "SETUP_S1_L1" => "Choose websites language",
  "SETUP_S1_B1" => "Accept language choice",
  "SETUP_S1_H1" => "After language choosing, the installation will continue in chosen language. This language will be set as main language for websites aswell.",
  "SETUP_S2_T1" => "Welcome in system installation",
  "SETUP_S2_T2" => "Thank you for using system <b>Domm Web Engine 7 (DWE7)</b>. System is created for the biggest optimalization and self working. 
    Next is comming a quick few steps installation which will be headed by system.",
  "SETUP_S2_B1" => "Continue in installation",
  "SETUP_S3_T1" => "Connect to database",
  "SETUP_S3_L1" => "Database server",
  "SETUP_S3_L1_P" => "Write here IP address/domain name of database server",
  "SETUP_S3_L2" => "Database name",
  "SETUP_S3_L2_P" => "Write here the database name",
  "SETUP_S3_L3" => "Database user",
  "SETUP_S3_L3_P" => "Write here the database user",
  "SETUP_S3_L4" => "User password",
  "SETUP_S3_L4_P" => "Write here user database password",
  "SETUP_S3_B1" => "Install database",
  "SETUP_S3_B1_H" => "This may take a while, system needs to configure and install database.",
  "SETUP_S4_T1" => "Basic websites configuration",
  "SETUP_S4_L1" => "Websites name",
  "SETUP_S4_L1_P" => "Write here your websites name",
  "SETUP_S4_L2" => "Websites E-Mail",
  "SETUP_S4_L2_P" => "Write here the website E-Mail address.",
  "SETUP_S4_B1" => "Configure websites",
  "SETUP_S5_T1" => "Create administrator",
  "SETUP_S5_L1" => "Login username",
  "SETUP_S5_L1_P" => "Write here the administrator login username",
  "SETUP_S5_L2" => "E-Mail address",
  "SETUP_S5_L2_P" => "Write here the administrators E-Mail address",
  "SETUP_S5_L3" => "Login password",
  "SETUP_S5_L3_P" => "Write here the administrators login password",
  "SETUP_S5_L4" => "Login password <i>(again)</i>",
  "SETUP_S5_L4_P" => "Write here the administrators login password",
  "SETUP_S5_B1" => "Create administrator account",
  "SETUP_S5_B1_H" => "Now you are about to create administrator account, thanks to which you can control websites.",
  "SETUP_S6_T1" => "Installation finished",
  "SETUP_S6_T2" => "System is now installed, you can continue to your websites, running on <b>Domm Web Engine 7 (DWE7)</b>.",
  "SETUP_S6_B1" => "Continue to website",
  "SETUP_S1_E1" => "No language pack was found, system can be damaged. Please try to upload this system on your web server once again.",
  "SETUP_S3_OK" => "Successfully connected to the database.",
  "SETUP_S3_E1" => "Problem with connection to database. (%s)",
  "ADMIN_T1" => "Administration",
  "ADMIN_WINDOW_1" => "Active",
  "ADMIN_WINDOW_2" => "Configuration",
  "ADMIN_WINDOW_3" => "Logout",
  "ADMIN_WINDOW_4" => "Last activity",
  "ADMIN_WINDOW_5" => "Show websites",
  "ADMIN_WINDOW_6" => "New post",
  "ADMIN_WINDOW_7" => "Show all",
  "ADMIN_WINDOW_8" => "<b>%s</b> wrote a comment to <b>%s</b>",
  "ADMIN_MENU_1" => "Main menu",
  "ADMIN_MENU_1_1" => "Notice-board",
  "ADMIN_MENU_2" => "Content management",
  "ADMIN_MENU_2_1" => "News",
  "ADMIN_MENU_2_2" => "News categories",
  "ADMIN_MENU_2_3" => "Comments",
  "ADMIN_MENU_2_4" => "Sites",
  "ADMIN_MENU_2_5" => "Uploaded files",
  "ADMIN_MENU_3" => "Users management",
  "ADMIN_MENU_3_1" => "Users",
  "ADMIN_MENU_3_2" => "User groups",
  "ADMIN_MENU_3_3" => "Mass message",
  "ADMIN_MENU_3_4" => "Report",
  "ADMIN_MENU_4" => "Websites configuration",
  "ADMIN_MENU_4_1" => "Main configuration",
  "ADMIN_MENU_4_2" => "Other configuration",
  "ADMIN_MENU_4_3" => "Sidebars management",
  "ADMIN_MENU_4_4" => "Plugins management",
  "ADMIN_MENU_4_5" => "Look",
  "ADMIN_MENU_4_6" => "Menu",
  "ADMIN_MENU_4_7" => "Actualizations",
  "ADMIN_MENU_5" => "Others",
  "ADMIN_LEAVE_1" => "You have been successfully logged out of administration.",
  "ADMIN_LEAVE_2" => "Your session expired, you were logged out of administration.",
  "ADMIN_DASHBOARD_T1" => "Notice-board",
  "ADMIN_DASHBOARD_T2" => "Users accounts",
  "ADMIN_DASHBOARD_T3" => "User groups",
  "ADMIN_DASHBOARD_T4" => "Posts",
  "ADMIN_DASHBOARD_T5" => "System version",
  "ADMIN_DASHBOARD_T6" => "Users",
  "ADMIN_DASHBOARD_T7" => "Files",
  "ADMIN_DASHBOARD_T8" => "Posts",
  "ADMIN_DASHBOARD_T9" => "DWE News",
  "ADMIN_DASHBOARD_L1" => "Number of users",
  "ADMIN_DASHBOARD_L2" => "Not activated users",
  "ADMIN_DASHBOARD_L3" => "Blocked users",
  "ADMIN_DASHBOARD_L4" => "Recently registered users",
  "ADMIN_DASHBOARD_L5" => "Uploaded files",
  "ADMIN_DASHBOARD_L6" => "Size of uploaded files",
  "ADMIN_DASHBOARD_L7" => "Number of news",
  "ADMIN_DASHBOARD_L8" => "Number of comments",
  "ADMIN_DASHBOARD_L9" => "Websites title",
  "ADMIN_DASHBOARD_L10" => "Look",
  "ADMIN_DASHBOARD_L11" => "Cannot load system news.",
  "ADMIN_DASHBOARD_L12" => "Number of websites",
  "ADMIN_DASHBOARD_B1" => "Show more",
  "ADMIN_AUTH_E1" => "Error in token authorization.",
  "ADMIN_AUTH_E2" => "Token authorization not found.",
  "ADMIN_AUTH_OK" => "Logging in to administration as <b>%s</b>.",
  "ADMIN_N1" => "You will be redirected to websites.",
  "ADMIN_N2" => "You will be redirected to administration websites.",
  "ADMIN_UP_T1" => "Uploaded files management",
  "ADMIN_UP_T2" => "Uploaded files",
  "ADMIN_UP_T3" => "Upload files",
  "ADMIN_UP_T4" => "Show file - %s",
  "ADMIN_UP_T5" => "This file preview is not supported.",
  "ADMIN_UP_L1" => "File title",
  "ADMIN_UP_L2" => "File type",
  "ADMIN_UP_L3" => "Link to file",
  "ADMIN_UP_B1" => "Upload file",
  "ADMIN_UP_B2" => "Back to uploaded files summary",
  "ADMIN_UP_B3" => "Delete file",
  "ADMIN_SB_T1" => "Sidebars management!",
  "ADMIN_SB_T2" => "Sidebars summary",
  "ADMIN_SB_T3" => "Sidebars update",
  "ADMIN_SB_T4" => "Sidebars delete",
  "ADMIN_SB_T5" => "You are going to delete sidebar <b>%s</b>. Delete is irrefutable.<br>Are you sure?",
  "ADMIN_SB_L1" => "active",
  "ADMIN_SB_L2" => "Sidebar title",
  "ADMIN_SB_L3" => "Sidebar caption",
  "ADMIN_SB_L4" => "Sidebar content",
  "ADMIN_SB_L4-1" => "No plugin with sidebar found",
  "ADMIN_SB_L5" => "Sidebar style",
  "ADMIN_SB_L6" => "Sidebars order",
  "ADMIN_SB_L7" => "Display sidebar",
  "ADMIN_SB_L8" => "Sidebars order",
  "ADMIN_SB_POS:top" => "Up",
  "ADMIN_SB_POS:bottom" => "Down",
  "ADMIN_SB_POS:left" => "Left",
  "ADMIN_SB_POS:right" => "Right",
  "ADMIN_SB_B1" => "Create sidebar",
  "ADMIN_SB_B2" => "Create sidebar from plugin",
  "ADMIN_SB_B3" => "Delete sidebar",
  "ADMIN_SB_B4" => "Update sidebar",
  "ADMIN_SB_B5" => "Bach to sidebars summary",
  "ADMIN_SB_B6" => "Do not delete",
  "ADMIN_SB_OK1" => "Sidebar  successfully updated",
  "ADMIN_SB_OK2" => "Sidebar bsuccessfully deleted",
  "ADMIN_NEWS_T1" => "Posts management",
  "ADMIN_NEWS_T2" => "Posts summary",
  "ADMIN_NEWS_T3" => "No category",
  "ADMIN_NEWS_T4" => "Posts update",
  "ADMIN_NEWS_T5" => "New post",
  "ADMIN_NEWS_T6" => "Publication configuration",
  "ADMIN_NEWS_T7" => "Date of creation",
  "ADMIN_NEWS_T8" => "Author",
  "ADMIN_NEWS_T9" => "Updated",
  "ADMIN_NEWS_T10" => "Posts delete",
  "ADMIN_NEWS_T11" => "You are going to delete post <b>%s</b>. Delete is irrefutable.<br>Are you sure?",
  "ADMIN_NEWS_T12" => "No link in this post, you cannot update it, but you can display it.",
  "ADMIN_NEWS_B1" => "New post",
  "ADMIN_NEWS_B2" => "Delete updates",
  "ADMIN_NEWS_B3" => "Show post",
  "ADMIN_NEWS_B4" => "Save changes",
  "ADMIN_NEWS_B5" => "Delete post",
  "ADMIN_NEWS_B6" => "Yes, delete post",
  "ADMIN_NEWS_B7" => "Do not delete",
  "ADMIN_NEWS_L1" => "Post title",
  "ADMIN_NEWS_L2" => "Author",
  "ADMIN_NEWS_L3" => "Category",
  "ADMIN_NEWS_L4" => "Date",
  "ADMIN_NEWS_L5" => "Post title",
  "ADMIN_NEWS_L6" => "Post category",
  "ADMIN_NEWS_L6N" => "No category",
  "ADMIN_NEWS_L7" => "Post content",
  "ADMIN_NEWS_L8" => "Post visibility",
  "ADMIN_NEWS_L8-1" => "Secret",
  "ADMIN_NEWS_L8-2" => "Public",
  "ADMIN_NEWS_L9" => "Comments",
  "ADMIN_NEWS_L10" => "Allow comments",
  "ADMIN_NEWS_L11" => "Link",
  "ADMIN_NEWS_L12" => "Whole link",
  "ADMIN_NEWS_L12-1" => "Use link: /<b>název_příspěvku</b>/",
  "ADMIN_NEWS_L12-2" => "Use link: /<b>ID_příspěvku</b>-<b>název_příspěvku</b>/",
  "ADMIN_NEWS_L12-3" => "Use link: /<b>rok</b>-<b>měsíc</b>-<b>den</b>-<b>název_příspěvku</b>/",
  "ADMIN_NEWS_L12-0" => "Use personal",
  "ADMIN_NEWS_L12-4" => "Use preset",
  "ADMIN_NEWS_L13" => "Post tags <i>(separate tags by <b>,</b>)</i>",
  "ADMIN_NEWS_L14" => "Post keywords <i>(separate keyboards by <b>,</b>)</i>",
  "ADMIN_NEWS_L15" => "Quick post content. <i>(no html)</i>",
  "ADMIN_NEWS_E1" => "No posts found.",
  "ADMIN_NEWS_OK1" => "Novelty updated.",
  "ADMIN_NEWS_OK2" => "Novelty deleted.",
  "ADMIN_MN_T1" => "Menu",
  "ADMIN_MN_T2" => "Menu summary",
  "ADMIN_MN_T3" => "Menu update",
  "ADMIN_MN_T4" => "Menu delete",
  "ADMIN_MN_T5" => "You are going to delete menu <b>%s</b>. Delete is irrefutable.<br>Are you sure?",
  "ADMIN_MN_T6" => "Link update",
  "ADMIN_MN_T7" => "You are going to delete link <b>%s</b>. Delete is irrefutable.<br>Are you sure?",
  "ADMIN_MN_T8" => "Delete link",
  "ADMIN_MN_T9" => "Menu category delete",
  "ADMIN_MN_T10" => "You are going to delete category <b>%s</b>. Delete is irrefutable.<br>Are you sure?",
  "ADMIN_MN_T11" => "Menu category update",
  "ADMIN_MN_L1" => "Menu update",
  "ADMIN_MN_L1-L" => "Select menu for update",
  "ADMIN_MN_L2" => "Primary menu",
  "ADMIN_MN_L3" => "New menu title",
  "ADMIN_MN_L4" => "Menu title",
  "ADMIN_MN_L5" => "Menu does not contain any categories or links.",
  "ADMIN_MN_L5-L" => "Category does not have any links, so it doesn\'t show.",
  "ADMIN_MN_L6" => "Link",
  "ADMIN_MN_L7" => "Order",
  "ADMIN_MN_L8" => "Link title",
  "ADMIN_MN_L9" => "Menu category title",
  "ADMIN_MN_B1" => "Update menu",
  "ADMIN_MN_B2" => "Set primary menu",
  "ADMIN_MN_B3" => "Create menu",
  "ADMIN_MN_B4" => "Close menu update",
  "ADMIN_MN_B5" => "Save menu title",
  "ADMIN_MN_B6" => "Create link",
  "ADMIN_MN_B7" => "Create category",
  "ADMIN_MN_B8" => "Update link",
  "ADMIN_MN_B9" => "Update category",
  "ADMIN_MN_B10" => "Delete menu",
  "ADMIN_MN_B11" => "Yes, delete menu",
  "ADMIN_MN_B12" => "Do not delete",
  "ADMIN_MN_B13" => "Delete link",
  "ADMIN_MN_B14" => "Delete category",
  "ADMIN_MN_D:L" => "Link",
  "ADMIN_MN_D:K" => "Category",
  "ADMIN_MN_N:L" => "New link",
  "ADMIN_MN_N:K" => "New category",
  "ADMIN_MN_OK1" => "Menu deleted.",
  "ADMIN_MN_OK2" => "Menu set as a primary.",
  "ADMIN_MN_OK3" => "Menu created.",
  "ADMIN_MN_OK4" => "Menu title updated.",
  "ADMIN_MN_OK5" => "Link updated.",
  "ADMIN_MN_OK6" => "Link deleted.",
  "ADMIN_MN_OK7" => "Category deleted from menu.",
  "ADMIN_MN_OK8" => "Category updated.",
  "ADMIN_MN_E1" => "Link in menu must be a link.",
  "ADMIN_MN_E2" => "The order of reference must be a number.",
  "ADMIN_NC_T1" => "Category management",
  "ADMIN_NC_T2" => "Category summary",
  "ADMIN_NC_T3" => "Category update",
  "ADMIN_NC_T4" => "Category delete",
  "ADMIN_NC_T5" => "You are going to delete category <b>%s</b>. Delete is irrefutable.<br>Are you sure?",
  "ADMIN_NC_T6" => "Category does not have its URL, so it can\'t be showed. But you can update it.",
  "ADMIN_NC_B1" => "Add category",
  "ADMIN_NC_B2" => "Discard changes",
  "ADMIN_NC_B3" => "Show category",
  "ADMIN_NC_B4" => "Save changes",
  "ADMIN_NC_B5" => "Delete category",
  "ADMIN_NC_B6" => "Yes, delete category",
  "ADMIN_NC_B7" => "Do not delete",
  "ADMIN_NC_L1" => "Category title",
  "ADMIN_NC_L2" => "Posts in category",
  "ADMIN_NC_L3" => "Category description",
  "ADMIN_NC_L4-1" => "posts",
  "ADMIN_NC_L4-2" => "post",
  "ADMIN_NC_L4-3" => "posts",
  "ADMIN_NC_L5" => "No description in this category",
  "ADMIN_NC_L6" => "Categroy title",
  "ADMIN_NC_L7" => "Category link",
  "ADMIN_NC_L8" => "Category description",
  "ADMIN_NC_OK1" => "Posts category successfully deleted.",
  "ADMIN_NC_OK2" => "Posts category successfully upadted.",
  "ADMIN_P_T1" => "Websites management",
  "ADMIN_P_T2" => "Websites summary",
  "ADMIN_P_T3" => "No update made.",
  "ADMIN_P_T4" => "Website update",
  "ADMIN_P_T5" => "Publication configuration",
  "ADMIN_P_T6" => "Date of creation",
  "ADMIN_P_T7" => "Author",
  "ADMIN_P_T8" => "Updated",
  "ADMIN_P_T9" => "Website delete",
  "ADMIN_P_T10" => "You are going to delete website <b>%s</b>. Delete is irrefutable.<br>Are you sure?",
  "ADMIN_P_T11" => "Site does not have its URL, so it can\'t be showed. But you can update it.",
  "ADMIN_P_L1" => "Website title",
  "ADMIN_P_L2" => "Website author",
  "ADMIN_P_L3" => "Date of creation",
  "ADMIN_P_L4" => "Last update",
  "ADMIN_P_L5" => "Website title",
  "ADMIN_P_L6" => "Website content",
  "ADMIN_P_L7" => "Website visibility",
  "ADMIN_P_L7-1" => "Unlisted",
  "ADMIN_P_L7-2" => "Public",
  "ADMIN_P_L8" => "Comments",
  "ADMIN_P_L9" => "Allow comments",
  "ADMIN_P_L10" => "Link",
  "ADMIN_P_B1" => "New site",
  "ADMIN_P_B2" => "Cancel updates",
  "ADMIN_P_B3" => "Show site",
  "ADMIN_P_B4" => "Save updates",
  "ADMIN_P_B5" => "Delete site",
  "ADMIN_P_B6" => "Yes, delete site",
  "ADMIN_P_B7" => "Do not delete",
  "ADMIN_P_OK1" => "Website deleted.",
  "ADMIN_P_OK2" => "Website updated.",
  "ADMIN_PL_T1" => "Plugins summary",
  "ADMIN_PL_T2" => "Plugins installation",
  "ADMIN_PL_T3" => "Plugin installation <b>%s</b>.",
  "ADMIN_PL_T4" => "Plugin installation file found",
  "ADMIN_PL_T5" => "Including plugin to active plugins",
  "ADMIN_PL_T6" => "Plugin bwill be deleted.",
  "ADMIN_PL_T6-2" => "Plugin bwill be deleted.",
  "ADMIN_PL_T7" => "Plugin uninstallation",
  "ADMIN_PL_T8" => "Plugin uninstallation <b>%s</b>",
  "ADMIN_PL_T9" => "Plugin configuration",
  "ADMIN_PL_T10" => "Plugin configuration <b>%s</b>",
  "ADMIN_PL_OK1" => "Plugin bwas successfully installed",
  "ADMIN_PL_OK2" => "Plugin bwas successfully installed",
  "ADMIN_PL_E1" => "Error in plugin installation",
  "ADMIN_PL_E2" => "Error in plugin uninstallation",
  "ADMIN_PL_B1" => "Informations",
  "ADMIN_PL_B2" => "Uninstallation",
  "ADMIN_PL_B3" => "Install",
  "ADMIN_PL_B4" => "Configuration",
  "ADMIN_PL_B5" => "Back to plugins summary",
  "ADMIN_C_T1" => "Comments",
  "ADMIN_C_T2" => "Comments management",
  "ADMIN_C_T3" => "Show comment",
  "ADMIN_C_T4" => "commented",
  "ADMIN_C_T5" => "Comment delete",
  "ADMIN_C_T6" => "Now you are going to delete comment from user <b>%s</b>, in post <b>%s</b>. <br> Are you sure?",
  "ADMIN_C_T7" => "Comment was successfully deleted.",
  "ADMIN_C_L1" => "User",
  "ADMIN_C_L2" => "Post",
  "ADMIN_C_L3" => "Date",
  "ADMIN_C_L4" => "Comment",
  "ADMIN_C_B1" => "Close comment preview",
  "ADMIN_C_B2" => "Delete comment",
  "ADMIN_C_B3" => "Yes, delete this comment",
  "ADMIN_C_B4" => "Do not delete",
  "ADMIN_M_T1" => "Mass message",
  "ADMIN_M_T2" => "New mass message",
  "ADMIN_M_T3" => "Sent mass messages",
  "ADMIN_M_OK1" => "Mass message was successfully sent to all users.",
  "ADMIN_M_E1" => "No sent mass messages.",
  "ADMIN_MS_T1" => "Main configuration",
  "ADMIN_MS_T2" => "Websites main configuration",
  "ADMIN_MS_L1" => "Websites title",
  "ADMIN_MS_L2" => "Websites E-Mail address",
  "ADMIN_MS_L3" => "Websites URL address",
  "ADMIN_MS_L4" => "Access protocol",
  "ADMIN_MS_L5" => "Basic websites language",
  "ADMIN_MS_L6" => "Website keywords <i>(keywords split with <b>,</b>)</i>",
  "ADMIN_MS_L7" => "About page description. <i>(no html)</i>",
  "ADMIN_MS_B1" => "Save configuration",
  "ADMIN_MS_OK" => "Configuration successfully saved.",
  "ADMIN_MS_E1" => "Website E-Mail address incorrect.",
  "ADMIN_MS_E2" => "Website URL incorrect.",
  "ADMIN_OS_T1" => "Other configuration",
  "ADMIN_OS_T2" => "Other websites configuration",
  "ADMIN_OS_L1" => "News URL configuration",
  "ADMIN_OS_L2" => "Number of news on page",
  "ADMIN_OS_L3" => "Number of comments on the principal display",
  "ADMIN_OS_L4" => "Maintance mod",
  "ADMIN_OS_L4l" => "Maintance mod description",
  "ADMIN_OS_L4-1" => "Shut down",
  "ADMIN_OS_L4-3" => "Only for full authorization",
  "ADMIN_OS_L5" => "Avatar size<i>(v px)</i>, aavatars are formed into squares",
  "ADMIN_OS_L6" => "Avatar size<i>(v byte)</i>",
  "ADMIN_OS_B1" => "Save configuration",
  "ADMIN_OS_OK" => "Configuration successfully saved.",
  "ADMIN_OS_E1" => "Hodnoty u počtu komentářů a novinek na stránce, musí být numerické.",
  "ADMIN_D_T1" => "Appearance configuration",
  "ADMIN_D_T2" => "Appearance summary",
  "ADMIN_D_T3" => "Appearance summary for administration",
  "ADMIN_D_T4" => "Appearance summary for websites",
  "ADMIN_D_T5" => "Author",
  "ADMIN_D_T6" => "This appearance is currently in use.",
  "ADMIN_D_T7" => "This theme does not contain any preview.",
  "ADMIN_D_T8" => "Theme has corrupted configuration file.",
  "ADMIN_D_T9" => "Theme has corrupted files.",
  "ADMIN_D_L1" => "Administration menu color",
  "ADMIN_D_L1-1" => "Dark",
  "ADMIN_D_L1-2" => "Light",
  "ADMIN_D_L2" => "Administration color",
  "ADMIN_D_L2-1" => "Blue",
  "ADMIN_D_L2-2" => "White",
  "ADMIN_D_L2-3" => "Purple",
  "ADMIN_D_L2-4" => "Green",
  "ADMIN_D_L2-5" => "Red",
  "ADMIN_D_L2-6" => "Yellow",
  "ADMIN_D_B1" => "Appearance adjustment",
  "ADMIN_D_B2" => "Basic appearance set",
  "ADMIN_D_B3" => "Set this appearance",
  "ADMIN_D_B4" => "Current appearance",
  "ADMIN_D_E1" => "You have to fill in all fields in administration configuration",
  "ADMIN_D_OK1" => "Websites appearance was successfully changed.",
  "ADMIN_U_T1" => "User management",
  "ADMIN_U_T2" => "Users summary",
  "ADMIN_U_T3" => "User profile",
  "ADMIN_U_T4" => "Avatar restart",
  "ADMIN_U_T5" => "You are going to restart avatar, user<b>%s</b>, basic avatar will be set to this user. User will be informed about this situation via E-Mail.",
  "ADMIN_U_T6" => "Block user",
  "ADMIN_U_T7" => "You are going to block user <b>%s</b>, user account will be blocked and it will be impossible to log in. User will be informed about this situation via E-Mail.",
  "ADMIN_U_T8" => "Delete user",
  "ADMIN_U_T9" => "You are going to delete user <b>%s</b>, sites and posts will be preserved, only comments and messages will be deleted. User will be informed about this situation via E-Mail.",
  "ADMIN_U_T10" => "Insufficient permission",
  "ADMIN_U_T11" => "Insufficient permission for showing profile with higher authorization.",
  "ADMIN_U_L1" => "Shown Username + <i>(uživatelské jméno)</i>",
  "ADMIN_U_L2" => "Primary group",
  "ADMIN_U_L3" => "Registration date",
  "ADMIN_U_L4" => "Last activity date",
  "ADMIN_U_L5" => "No primary group",
  "ADMIN_U_L6" => "Username",
  "ADMIN_U_L7" => "Shown Username",
  "ADMIN_U_L8" => "User avatar",
  "ADMIN_U_L9" => "User E-Mail",
  "ADMIN_U_L10" => "User signature",
  "ADMIN_U_L11" => "Primary group",
  "ADMIN_U_L12" => "Avatar delete reason",
  "ADMIN_U_L13" => "Basic user rights",
  "ADMIN_U_L14" => "User block reason",
  "ADMIN_U_L15" => "User delete reason",
  "ADMIN_U_L16" => "Is member of one group (<strong>%s</strong>).",
  "ADMIN_U_L17" => "Not member of any group yet",
  "ADMIN_U_B1" => "Delete user profile",
  "ADMIN_U_B2" => "Reset avatar",
  "ADMIN_U_B3" => "Show profile",
  "ADMIN_U_B4" => "Block user",
  "ADMIN_U_B5" => "Delete user",
  "ADMIN_U_B6" => "Do not reset avatar",
  "ADMIN_U_B7" => "Save changes",
  "ADMIN_U_B8" => "Block user",
  "ADMIN_U_B9" => "Do not block user",
  "ADMIN_U_B10" => "Delete user",
  "ADMIN_U_B11" => "Do not delete users",
  "ADMIN_U_B12" => "Back to users summary",
  "ADMIN_U_OK1" => "Profile image <i>(User avatar)</i>, was restarted.",
  "ADMIN_U_OK2" => "User account successfully blocked.",
  "ADMIN_U_OK3" => "User account successfully deleted.",
  "ADMIN_U_OK4" => "User account was successfully updated.",
  "ADMIN_UG_T1" => "Group management",
  "ADMIN_UG_T2" => "User groups summary",
  "ADMIN_UG_T3" => "Group members",
  "ADMIN_UG_T4" => "Group management - %s",
  "ADMIN_UG_T5" => "No members in this group.",
  "ADMIN_UG_T6" => "Group delete",
  "ADMIN_UG_T7" => "You are going to delete user group <b>%s</b>. This delete is irrefutable.<br>Are you sure?",
  "ADMIN_UG_T8" => "Add member to group",
  "ADMIN_UG_T9" => "Group doesn\'t have completed link, thats why it\'s not visible and no member can\'t be added in. But you can update it\'s description.",
  "ADMIN_UG_L1" => "Group",
  "ADMIN_UG_L2" => "Group tags",
  "ADMIN_UG_L3" => "Group members",
  "ADMIN_UG_L4" => "User",
  "ADMIN_UG_L5" => "Action",
  "ADMIN_UG_L6" => "Group name",
  "ADMIN_UG_L7" => "Text on Tag",
  "ADMIN_UG_L8" => "tags color",
  "ADMIN_UG_L9" => "Text and tags color",
  "ADMIN_UG_L10" => "Group link",
  "ADMIN_UG_L11" => "Group description",
  "ADMIN_UG_L12" => "Username",
  "ADMIN_UG_L12-L" => "Type in here username.",
  "ADMIN_UG_B1" => "New group",
  "ADMIN_UG_B2" => "back to group management",
  "ADMIN_UG_B3" => "Delete from group",
  "ADMIN_UG_B4" => "Add user",
  "ADMIN_UG_B5" => "Save changes",
  "ADMIN_UG_B6" => "Show group",
  "ADMIN_UG_B7" => "Delete group",
  "ADMIN_UG_B8" => "Yes, delete this group.",
  "ADMIN_UG_B9" => "Do not delete.",
  "ADMIN_UG_B10" => "Add member",
  "ADMIN_UG_B11" => "Bach to group management",
  "ADMIN_UG_OK1" => "User group was successfully deleted.",
  "ADMIN_UG_OK2" => "User was successfully added to group.",
  "ADMIN_UG_OK3" => "User group was successfully updated.",
  "ADMIN_UG_E1" => "User wasn\'t found.",
  "ADMIN_RP_T1" => "Report management",
  "ADMIN_RP_T2" => "Report summary",
  "ADMIN_RP_T3" => "Report detail",
  "ADMIN_RP_T4" => "Report management",
  "ADMIN_RP_T5" => "Report message",
  "ADMIN_RP_T5-L" => "Message for user, who reported.",
  "ADMIN_RP_T6" => "Delete report",
  "ADMIN_RP_T7" => "You are going to delete report <b>%s</b>. This delete is irrefutable.<br>Are you sure?",
  "ADMIN_RP_T8" => "Solved reports",
  "ADMIN_RP_L1" => "Report",
  "ADMIN_RP_L2" => "Report type",
  "ADMIN_RP_L3" => "User",
  "ADMIN_RP_L4" => "Report date",
  "ADMIN_RP_L5" => "Seen",
  "ADMIN_RP_L5-1" => "Report seen",
  "ADMIN_RP_L5-2" => "Report solved",
  "ADMIN_RP_N_TYPE_user" => "<b>%s</b> reported user <b>%s</b>.",
  "ADMIN_RP_N_TYPE_comment" => "<b>%s</b> reported comment.",
  "ADMIN_RP_TYPE_user" => "Report user",
  "ADMIN_RP_TYPE_comment" => "Report comment",
  "ADMIN_RP_OK1" => "Report was successfully deleted.",
  "ADMIN_RP_OK2" => "Report was successfully solved.",
  "ADMIN_RP_E1" => "Message from report does not exist.",
  "ADMIN_RP_B1" => "Solve report",
  "ADMIN_RP_B2" => "Delete report",
  "ADMIN_RP_B3" => "Do not delete report",
  "ADMIN_RP_MESSAGE" => "<b>Message from report</b><br>
    Report sent: <b>%s</b><br>
    <b>%s</b><br>
    <b>Report text:</b><br>
    %s
    <hr>
    Report solved - <b>%s</b> - %s<br>
    <b>Message from report:</b><br>
    %s
    ",
  "ADMIN_R_T1" => "Authorization management",
  "ADMIN_R_T2" => "a = user | b - y = own configuration (b < y)  | z = full authorization",
  "ADMIN_R_R:NONE" => "Basic authorization",
  "ADMIN_R_R:CUSTOM" => "Own configuration",
  "ADMIN_R_R:FULL" => "Full authorization",
  "ADMIN_R_L0" => "Authorization",
  "ADMIN_R_web_access" => "Websites access.",
  "ADMIN_R_administration_access" => "Administration access.",
  "ADMIN_R_administration_news" => "News management",
  "ADMIN_R_administration_news_categories" => "News category management",
  "ADMIN_R_administration_comments" => "Comments management",
  "ADMIN_R_administration_pages" => "Sites management",
  "ADMIN_R_administration_uploads" => "Uploaded files management",
  "ADMIN_R_administration_users" => "Users management",
  "ADMIN_R_administration_usergroups" => "User groups management",
  "ADMIN_R_administration_message" => "Mass messages",
  "ADMIN_R_administration_reports" => "Reports management",
  "ADMIN_R_administration_main_settings" => "Access to websites configuration",
  "ADMIN_R_administration_other_settings" => "Access to additional websites configuration",
  "ADMIN_R_administration_sidebars" => "Sidebar management",
  "ADMIN_R_administration_plugins" => "Plugin management",
  "ADMIN_R_administration_design" => "Design management",
  "ADMIN_R_administration_menu" => "Menu management",
  "ADMIN_R_administration_update" => "Websites update management",
  "ADMIN_R_B1" => "Save authorization",
  "ADMIN_R_B2" => "Set basic authorization",
  "ADMIN_R_OK" => "Authorization was successfully saved.",
  "ADMIN_E_C" => "Error!",
  "ADMIN_E_W" => "Attention",
  "ADMIN_E_S" => "Success!",
  "ADMIN_E_I" => "Info",
  "ADMIN_E_E1" => "You didn\'t fill in all fields",
  "ADMIN_DEFAULT_NAME:POST_TYPE_NEWS" => "New post",
  "ADMIN_DEFAULT_NAME:POST_TYPE_PAGE" => "New site",
  "ADMIN_DEFAULT_NAME:NEWS_CATEGORY" => "New category",
  "ADMIN_DEFAULT_NAME:SIDEBAR" => "New sidebar",
  "ADMIN_DEFAULT_NAME:USER_GROUP" => "New user group",
  "E_EMAIL_ACCOUNT_BLOCK" => "<h1>Account blocation %s</h1>

    Your user account <b>%s</b> on <b>%s</b>, was blocked.

    <br>
    <p>%s</p>
    <br>
    This E-Mail is just informative.
    ",
  "E_EMAIL_ACCOUNT_REMOVE" => "<h1>Account delete %s</h1>

    Your user account <b>%s</b> on <b>%s</b>, was deleted from following reasons.

    <br>
    <p>%s</p>
    <br>
    This E-Mail is just informative.
    ",
  "E_EMAIL_REGISTER" => "<h1>Registration on %s</h1>

    Your E-Mail was used in registration on %s.
    <br>
    <br>
    <b>Username:</b> %s
    <br>
    <b>Password:</b> %s
    <br>
    <b>Activation link:</b> %s
    <br>
    <br>
    <b>If you don\'t know what this message is and you didn\'t applied for new password, just ignore this message please.</b><br>
    This request will be automatically deleted after 24hours from request.",
  "E_ACTIVATE_ACCOUNT" => "<h1>Account activation on %s</h1>

    Your E-Mail was used in account activation on %s.
    <br>
    <br>
    <b>Username:</b> %s
    <br>
    <b>Activation link:</b> %s
    <br>
    <br>
    <b>If you don\'t know what this message is and you didn\'t applied for new password, just ignore this message please.</b><br>
    This request will be automatically deleted after 24hours from request.",
  "E_ACTIVATED_ACCOUNT" => "<h1>Account activation on %s</h1>

    Your user account on %s, was activated by this E-Mail address.
    <br>
    <br>
    <b>Username:</b> %s
    <br>
    <br>
    This E-Mail address is now verificated with user <b>%s</b>.",
  "E_PASSWORD_LOST" => "<h1>Forgotten password on %s</h1>

    Request for password change on %s was successfully created.
    <br>
    <br>
    <b>Username:</b> %s
    <br>
    <b>Link for password change:</b> %s
    <br>
    <br>
    <b>If you don\'t know what this message is and you didn\'t applied for new password, just ignore this message please.</b><br>
    This request will be automatically deleted after 24hours from request.",
  "E_PASSWORD_CHANGE" => "<h1>Forgotten passsword on %s</h1>

    Your password on %s wass successfully changed",
  "E_PASSWORD_CLOSE" => "<h1>Forgotten password on %s</h1>

    Request for password change on %s was successfully deleted.",
  "E_EMAIL_CHANGE" => "<h1>E-Mail address change on %s</h1>

    Request for E-Mail change on %s was successfully created<br>

    <br>
    <b>Username:</b> %s<br>

    <b>New E-Mail:</b> %s<br>

    <b>Link for change confirmation:</b> %s<br>

    <br>
    <b>If you don\'t know what this message is and you didn\'t applied for new password, just ignore this message please.</b><br>
    This request will be automatically deleted after 24hours from request.",
  "E_EMAIL_CHANGED" => "<h1>E-Mail address change%s</h1>

    Your E-Mail address on site %s was successfully changed to <b>%s</b>.",
  "E_PASS_CHANGE" => "<h1>User password change on %s</h1>

    Request for password change on %s was successfully created<br>

    <br>
    <b>Username:</b> %s<br>

    <b>Link for change confirmation:</b> %s<br>

    <br>
    <b>If you don\'t know what this message is and you didn\'t applied for new password, just ignore this message please.</b><br>
    This request will be automatically deleted after 24hours from request.",
  "E_PASS_CHANGED" => "<h1>Change user password %s</h1>

    Your user password on site  %s was successfully changed.",
  "E_EMAIL_END" => "Greetings,
    <br><b>%s</b>",
  "USER_ROLE_banned" => "Blocked user",
  "USER_ROLE_unactive" => "Unactivated user",
  "USER_ROLE_user" => "User",
  "USER_ROLE_moderator" => "Moderator",
  "USER_ROLE_main_moderator" => "Main moderator",
  "USER_ROLE_administrator" => "Administrator",
  "USER_ROLE_main_administrator" => "Main administrator",
  "T_YEAR" => "year",
  "T_B_YEAR" => "years",
  "T_B_YEAR_P" => "years",
  "T_MONTH" => "month",
  "T_B_MONTH" => "months",
  "T_B_MONTH_P" => "months",
  "T_DAY" => "day",
  "T_B_DAY" => "days",
  "T_B_DAY_P" => "days",
  "T_HOUR" => "hour",
  "T_B_HOUR" => "hours",
  "T_B_HOUR_P" => "hours",
  "T_MINUTE" => "minute",
  "T_B_MINUTE" => "minutes",
  "T_B_MINUTE_P" => "minutes",
  "T_SECOND" => "second",
  "T_B_SECOND" => "seconds",
  "T_B_SECOND_P" => "seconds",
  "T_NOW" => "Right now",
  "T_BEFORE" => "Before",
  "OTHER_1-1" => "a %d another users",
  "OTHER_1-2" => "a %d another users",
  "OTHER_1-3" => "a one another user",
));
?>